### PR TITLE
Add symbols and pdb opts

### PR DESCRIPTION
**Pull request by sbatten**

### CODE REVIEW

**Comment by joaomoreno** [comment]
What is this for? Could we perhaps stop contributing to this repo?

**Comment by deepak1556** [comment]
> Could we perhaps fetch these in some other way other than adding to this deprecated repo?

why is the repo deprecated 😄  ? Isn't it the only way we currently consume electron bits for vscode ?

**Comment by joaomoreno** [comment]
This was created back when there was no official way to download Electron. There are official ways today which we should probably just start using... just needs someone to do that adoption. I did not test these changes, but I trust you for them to work.

**Comment by joaomoreno** [comment]
After merging, I noticed a few things:

1. The tests have been broken for a long time
2. They are still broken
3. There is [a lost `console.log` statement](https://github.com/joaomoreno/gulp-atom-electron/blob/1b1906fc147b279b8559dfd24ebfee2243db9d12/test/download.test.js#L36) in this PR
4. That `console.log` shows a potential problem with the feature this PR brings, look at the paths that the tests print out:

```
LICENSE
LICENSES.chromium.html
version
breakpad_symbols/electron.exe.pdb/77C57ADEE7D5B8CA4C4C44205044422E1/electron.exe.sym
breakpad_symbols/libEGL.dll.pdb/7ED08B266FA3C2644C4C44205044422E1/libEGL.dll.sym
breakpad_symbols/libGLESv2.dll.pdb/8F38632F0DAC76A34C4C44205044422E1/libGLESv2.dll.sym
```

Those can't be right. Is `electron.exe.pdb` really a folder?

For these reasons, I didn't release a new version of this.

**Comment by sbatten** [comment]
@joaomoreno the paths are right. there are 2 types of symbols packages from electron: symbols and pdb. the symbols package has the structure seen above. the pdb has the actual pdb files. sorry about the console log

**Pull request merged**
